// 超级管理员类型
export const PERSON_TYPE = {
  LEGAL: "LEGAL", //  经营者/法定代表人
  SUPER: "SUPER" //  经办人
};

// 证件类型
export const IDENTIFICATION_TYPE = {
  IDCARD: "IDENTIFICATION_TYPE_IDCARD", // 身份证
  OVERSEA_PASSPORT: "IDENTIFICATION_TYPE_OVERSEA_PASSPORT", // 护照
  HONGKONG_PASSPORT: "IDENTIFICATION_TYPE_HONGKONG_PASSPORT", // 中国香港居民-来往内地通行证
  MACAO_PASSPORT: "IDENTIFICATION_TYPE_MACAO_PASSPORT", // 中国澳门居民-来往内地通行证
  TAIWAN_PASSPORT: "IDENTIFICATION_TYPE_TAIWAN_PASSPORT", // 中国台湾居民-来往大陆通行证
  FOREIGN_RESIDENT: "IDENTIFICATION_TYPE_FOREIGN_RESIDENT", // 外国人居留证
  HONGKONG_MACAO_RESIDENT: "IDENTIFICATION_TYPE_HONGKONG_MACAO_RESIDENT", // 港澳居民居住证
  TAIWAN_RESIDENT: "IDENTIFICATION_TYPE_TAIWAN_RESIDENT" // 台湾居民居住证
};

// 主体类型
export const SUBJECT_TYPE = {
  INDIVIDUAL: "SUBJECT_TYPE_INDIVIDUAL", // 个体户
  ENTERPRISE: "SUBJECT_TYPE_ENTERPRISE", // 企业
  GOVERNMENT: "SUBJECT_TYPE_GOVERNMENT", // 政府机关
  INSTITUTIONS: "SUBJECT_TYPE_INSTITUTIONS", // 事业单位
  OTHERS: "SUBJECT_TYPE_OTHERS", // 其他组织
};

// 金融机构类型
export const FINANCE_TYPE = {
  BANK_AGENT: "BANK_AGENT", // 银行业
  PAYMENT_AGENT: "PAYMENT_AGENT", // 支付机构
  INSURANCE: "INSURANCE", // 保险业
  TRADE_AND_SETTLE: "TRADE_AND_SETTLE", // 交易及结算类金融机构
  OTHER: "OTHER", // 其他金融机构
};

// 销售场景类型
export const SALES_SCENE_TYPE = {
  SALES_SCENES_STORE: "SALES_SCENES_STORE", // 线下场所
  SALES_SCENES_MP: "SALES_SCENES_MP", // 服务号与公众号
  SALES_SCENES_MINI_PROGRAM: "SALES_SCENES_MINI_PROGRAM", // 小程序
  SALES_SCENES_WEB: "SALES_SCENES_WEB", // 互联网网站
  SALES_SCENES_APP: "SALES_SCENES_APP", // App
  SALES_SCENES_WEWORK: "SALES_SCENES_WEWORK", // 企业微信
};


// 银行账户类型
export const BANK_ACCOUNT_TYPE = {
  CORPORATE: "BANK_ACCOUNT_TYPE_CORPORATE", // 对公银行账户
  PERSONAL: "BANK_ACCOUNT_TYPE_PERSONAL", // 经营者个人银行卡
}